PRAS-Task/Controllers/EngNewsController.cs
using Microsoft.AspNetCore.Mvc;
using PRAS_Task.Data.Models;
using PRAS_Task.Data;
using Microsoft.AspNetCore.Authorization;

namespace PRAS_Task.Controllers
{
    public class EngNewsController : Controller
    {
        DataContext _context;
        IWebHostEnvironment _environment;
        public EngNewsController(DataContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }
        [HttpGet]
        [Authorize]
        public ActionResult Index()
        {
            var news = _context.EngNews.ToList<EngNew>();
            return View("Index", news);
        }
        [HttpPost]
        [Authorize]
        public async Task<ActionResult> Create(EngNew _new)
        {

            var uploadPath = $"{_environment.WebRootPath}/images";
            var files = Request.Form.Files;
            string filePath;
            if (files[0] != null)
            {
                filePath = @$"{uploadPath}/{files[0].FileName}";
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await files[0].CopyToAsync(fileStream);

                }
                _new.picture = files[0].FileName;
                _new.date = DateTime.Now;
                _context.EngNews.Add(_new);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return BadRequest("Error");

        }
        [Authorize]
        [HttpGet]
        public async Task<ActionResult> CreateView()
        {
            return View("Create");
        }

        [HttpPost]
        [Authorize]
        public ActionResult Delete(int Newid)
        {

            var data = _context.EngNews.Where(x => x.Id == Newid).FirstOrDefault();
            if (data != null)
            {
                _context.EngNews.Remove(data);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
                return BadRequest("Cant delete");
        }
        [Authorize]
        public ActionResult UpdateView(int id)
        {
            var _new = _context.EngNews.Where(x => x.Id == id).FirstOrDefault();
            if (_new != null)
            {
                return View("Update", _new);
            }
            return BadRequest("Not exist");
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> Update(EngNew model)
        {
            var data = _context.EngNews.Where(x => x.Id == model.Id).FirstOrDefault();

            if (data != null)
            {
                var files = Request.Form.Files;
                string filePath = "";
                string oldPath;
                if (files.Count > 0)
                {
                    oldPath = model.picture;

                    var uploadPath = Path.Combine($"{_environment.WebRootPath}", "images");
                    filePath = $"{uploadPath}/{files[0].FileName}";
                    if (oldPath != filePath)
                    {
                        using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            await files[0].CopyToAsync(fileStream);
                        }
                        model.picture = files[0].FileName;
                        data.picture = model.picture;
                    }

                }

                data.text = model.text;
                data.name = model.name;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
                return BadRequest("Error during processing data");
        }
    }
}

PRAS-Task/Controllers/NewsController.cs
using Microsoft.AspNetCore.Mvc;
using PRAS_Task.Data;

namespace PRAS_Task.Controllers
{
    public class NewsController : Controller
    {
        IdentityContext _context;
        public NewsController(IdentityContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

PRAS-Task/Views/EngNews/Create.cshtml
@using PRAS_Task.Data.Models;
@model EngNew;

<form asp-action="Create" asp-controller="EngNews" enctype="multipart/form-data">
    <div>
        <div class="form-group">
            <label>Title </label>
            <input type="text" asp-for="name" class="form-control form-control-sm" />
        </div>
        <div class="form-group">
            <label> Photo</label>
            <input asp-for="picture" type="file" class="form-control  form-control-sm" />
        </div>
        <div class="form-group">
            <label>Text </label>
            <textarea asp-for="text" class="form-control  form-control-sm"></textarea>
        </div>
        <div class="form-group">
            <input class="btn btn-success btn-outline-dark" type="submit" value="Save" class="btn btn-success" />
        </div>
    </div>
</form>

<div>
    <button class="btn btn-primary btn-outline-dark">
        <a style="color: white; text-decoration: none;" asp-controller="EngNews" asp-action="Index">Back</a>
    </button>
</div>

PRAS-Task/Views/EngNews/Index.cshtml
@using PRAS_Task.Data.Models;
@model IEnumerable<EngNew>;
<button class="btn btn-secondary">
	<a asp-action ="Index" asp-controller="News">
Статьи на русском
</a></button>
@if (Model.Any())
{

    <table class="table table-hover">

        <tr>
            <th scope="col">Id</th>
            <th scope="col"><a asp-controller="News" asp-action="Index">Title</a></th>
            <th scope="col"><a asp-controller="News" asp-action="Index">Date</a> </th>
            <th></th>
            <th></th>

        </tr>
        @foreach (var item in Model)
        {
            <tr class="table-primary">
                <td>@item.Id</td>
                <td>@item.name</td>
                <td>@item.date</td>
                <td>
                    <form method="post" asp-controller="EngNews" asp-action="Delete" asp-route-Newid="@item.Id">
                        <button class="btn btn-danger" type="submit">Delete</button>
                    </form>
                </td>
                <td>
                    <form method="post" asp-controller="EngNews" asp-action="UpdateView" asp-route-id="@item.Id">
                        <button class="btn btn-secondary" type="submit">Edit</button>
                    </form>
                </td>
            </tr>
        }
    </table>

    <button type="submit" class="btn-success">
        <a asp-action="CreateView" asp-controller="EngNews" style="text-decoration: none; color:white">Create news</a>
    </button>

}
else
{
    <h3 class="">There are no any news in your data base. Click <a asp-action="CreateView" asp-controller="EngNews">here</a> to create first</h3>
}

PRAS-Task/Views/EngNews/Update.cshtml
@using PRAS_Task.Data.Models;
@model EngNew;

<form asp-action="Update" asp-controller="EngNews" enctype="multipart/form-data">
    <div>
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label>Model Name:</label>
            <input type="text" asp-for="name" class="form-control form-control-sm" />
        </div>
        <div class="form-group">
            <img runat="server" src="~/images/@Model.picture" height="400" />
        </div>
        <div class="form-group">
            <label> Change photo</label>
            <input asp-for="picture" type="file" class="form-control  form-control-sm" />
        </div>
        <div class="form-group">
            <label>Text of article</label>
            <textarea asp-for="text" class="form-control  form-control-sm"></textarea>
        </div>
        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-success btn-outline-dark" />
        </div>
    </div>
</form>